### ISSUE TITLE
Import Contained Database Fails

### ISSUE THREAD

**Issue by maxsaseg** [mathworks-ref-arch/matlab-database-testing-framewor#1]
Hi and thanks for the toolbox.
However, I can't import a backup of a (contained) MS SQL database getting the following error:

> tc.importBackupFile("DriftKontrol.bak")
> Error using database.odbc.connection/executeHook
> ODBC Driver Error: ODBC Driver Error: [Microsoft][ODBC SQL Server Driver][SQL Server]Database 'DatabaseTesting' does not exist. Make sure
> that the name is entered correctly.
> Error in database.relational.connection/execute (line 257)
> connect.executeHook(second_input);
> Error in dbtest.fixtures.MsSqlServer/importDatabase (line 74)
> db.execute("USE " + this.TestingDatabase);
> Error in dbtest.fixtures.DockerDatabase/importBackupFile (line 175)
> this.importDatabase("/tmp/" + file);
> Error in dbtest.WithDatabase/importBackupFile (line 39)
> this.getDbServerFixture().importBackupFile(varargin{:});

I've managed to get it running with the same database that I create using a script (viz. task - generate scripts in SSMS) that creates schemes and tables with data, but not users. 
The following in an app works nicely

> if ~app.USE_DOCKER
> 	app.conn = openConnection;
> else
> 	app.tc = dbtest.WithMsSqlServer2019.forInteractiveUseWithAutoSetup();
> 	app.conn =  app.tc.DatabaseConnection; 
> 	ProgressDlg.Message = 'Opretter Docker database';
> 	drawnow;
> 	resp = app.conn.executeSQLScript(which('createDb.sql')); % Load DB
> 	isEmpty = all(arrayfun(@(x) isempty([resp.Message]), resp));
> 	if ~isEmpty
> 		error('COMPOST:Database:connection_error', 'Der skete en fejl ved oprettelsen af DB');
> 	end
> end

The .bak file is on my matlab path:
 

> which("DriftKontrol.bak")
> C:\Users\max\OneDrive - ERA Data Science ApS\Documents\MATLAB\DriftKontrol.bak
> I

It would however be nice to import the backup. Any thoughts on what might be the problem? User rights in the created database?
BR

**Comment by timjohns-mw** [comment]
Hi @maxsaseg - sorry for not responding to this. For some reason I didn't get an alert from GitHub and I've only just found your issue. Thank you for giving the DB testing framework a go!

Did you manage to resolve this issue or are you still having difficulty?

**Comment by maxsaseg** [comment]
Hi @timjohns-mw no worries, thanks for getting back.
Yes I solved the issue, even though I don't quite recall how, believe it was something about starting the container and then running a SQL script loading the entire database without user info...
BR Max

**Comment by timjohns-mw** [comment]
Great, glad to hear it!
